-- Create lead distribution settings table
CREATE TABLE IF NOT EXISTS public.lead_distribution_settings (
  agent_id UUID PRIMARY KEY REFERENCES public.profiles(id) ON DELETE CASCADE,
  percentage INTEGER NOT NULL CHECK (percentage >= 1 AND percentage <= 100),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- RLS for settings
ALTER TABLE public.lead_distribution_settings ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Admins can select lead distribution settings"
ON public.lead_distribution_settings
FOR SELECT TO authenticated
USING (public.has_role(auth.uid(), 'admin'));

CREATE POLICY "Admins can insert lead distribution settings"
ON public.lead_distribution_settings
FOR INSERT TO authenticated
WITH CHECK (public.has_role(auth.uid(), 'admin'));

CREATE POLICY "Admins can update lead distribution settings"
ON public.lead_distribution_settings
FOR UPDATE TO authenticated
USING (public.has_role(auth.uid(), 'admin'))
WITH CHECK (public.has_role(auth.uid(), 'admin'));

CREATE POLICY "Admins can delete lead distribution settings"
ON public.lead_distribution_settings
FOR DELETE TO authenticated
USING (public.has_role(auth.uid(), 'admin'));

CREATE POLICY "Agents can view lead distribution settings"
ON public.lead_distribution_settings
FOR SELECT TO authenticated
USING (true);

-- Create lead distribution tickets table
CREATE TABLE IF NOT EXISTS public.lead_distribution_tickets (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  agent_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  used BOOLEAN NOT NULL DEFAULT false,
  used_at TIMESTAMPTZ,
  sort_order FLOAT NOT NULL DEFAULT random(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- RLS for tickets
ALTER TABLE public.lead_distribution_tickets ENABLE ROW LEVEL SECURITY;

-- Admins can view/manage
CREATE POLICY "Admins can manage distribution tickets"
ON public.lead_distribution_tickets
FOR ALL TO authenticated
USING (public.has_role(auth.uid(), 'admin'));

-- Function to generate 100 tickets based on percentages
CREATE OR REPLACE FUNCTION public.regenerate_lead_tickets()
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  total_percentage INTEGER;
  r RECORD;
BEGIN
  -- We only regenerate if total sum is 100
  SELECT SUM(percentage) INTO total_percentage FROM public.lead_distribution_settings;
  
  -- Delete unused tickets
  DELETE FROM public.lead_distribution_tickets WHERE used = false;

  IF coalesce(total_percentage, 0) = 100 THEN
    FOR r IN SELECT agent_id, percentage FROM public.lead_distribution_settings LOOP
      FOR i IN 1..r.percentage LOOP
        INSERT INTO public.lead_distribution_tickets (agent_id, sort_order)
        VALUES (r.agent_id, random());
      END LOOP;
    END LOOP;
  END IF;
END;
$$;

CREATE OR REPLACE FUNCTION public.trigger_regenerate_lead_tickets()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  PERFORM public.regenerate_lead_tickets();
  RETURN NULL;
END;
$$;

-- Trigger to call the generation function whenever settings are modified
DROP TRIGGER IF EXISTS on_lead_distribution_settings_change ON public.lead_distribution_settings;
CREATE TRIGGER on_lead_distribution_settings_change
  AFTER INSERT OR UPDATE OR DELETE ON public.lead_distribution_settings
  FOR EACH STATEMENT
  EXECUTE FUNCTION public.trigger_regenerate_lead_tickets();

-- Function to get the next lead agent and consume the ticket
CREATE OR REPLACE FUNCTION public.get_next_lead_agent()
RETURNS UUID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  next_ticket RECORD;
  selected_agent_id UUID;
BEGIN
  -- Find the next available ticket implicitly sorting by sort_order
  SELECT * INTO next_ticket
  FROM public.lead_distribution_tickets
  WHERE used = false
  ORDER BY sort_order ASC
  LIMIT 1
  FOR UPDATE SKIP LOCKED;

  IF FOUND THEN
    -- Consume the ticket
    UPDATE public.lead_distribution_tickets
    SET used = true, used_at = now()
    WHERE id = next_ticket.id;
    
    selected_agent_id := next_ticket.agent_id;
  ELSE
    -- If no tickets available, try to lock and regenerate
    -- Use advisory locks to prevent multiple concurrent generations
    IF pg_try_advisory_xact_lock(hashtext('regenerate_lead_tickets')) THEN
        -- Check again if tickets were generated by another transaction
        SELECT * INTO next_ticket
        FROM public.lead_distribution_tickets
        WHERE used = false
        ORDER BY sort_order ASC
        LIMIT 1
        FOR UPDATE SKIP LOCKED;
        
        IF NOT FOUND THEN
            PERFORM public.regenerate_lead_tickets();
            
            -- Try to fetch one more time
            SELECT * INTO next_ticket
            FROM public.lead_distribution_tickets
            WHERE used = false
            ORDER BY sort_order ASC
            LIMIT 1
            FOR UPDATE SKIP LOCKED;
        END IF;
        
        IF FOUND THEN
            UPDATE public.lead_distribution_tickets
            SET used = true, used_at = now()
            WHERE id = next_ticket.id;
            selected_agent_id := next_ticket.agent_id;
        END IF;
    END IF;
  END IF;

  -- Fallback logic
  IF selected_agent_id IS NULL THEN
    SELECT default_agent_id INTO selected_agent_id FROM public.chatbot_settings LIMIT 1;
    
    IF selected_agent_id IS NULL THEN
      SELECT agent_id INTO selected_agent_id FROM public.lead_distribution_settings LIMIT 1;
    END IF;
    
    IF selected_agent_id IS NULL THEN
      SELECT user_id INTO selected_agent_id FROM public.user_roles WHERE role = 'admin' LIMIT 1;
    END IF;
  END IF;

  RETURN selected_agent_id;
END;
$$;
