// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jnqhbeadqrvfcewlznlj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpucWhiZWFkcXJ2ZmNld2x6bmxqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI3Mjg5MjYsImV4cCI6MjA4ODMwNDkyNn0.xHlhq8_8LRmYqf9dnbcI3aFsU3bq53qQh7FgzSatRO4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});